url: https://timsherq.co.za
enforce_ssl: timsherq.co.za
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
  - jekyll-sitemap
  - jekyll-seo-tag
  webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
