// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "Home: Tim SHERQ", "ADDRESS Unit  22  Kloofberg Business Park   17 Spruit Street  Germiston  1401 CONTACTS Email  info@timsherq.co.za Phone  +27 81 413 5910 Fax      +27 86 410 7887   WhatsApp  +27 81 413 5910   Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("about-us.html", "About Us:  Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ Consultancy  Providing, practical innovations on  Safety, Health, Environment, Risk & Quality  SHERQ ");
   this[database_length++] = new SearchPage("training.html", "Training: Tim SHERQ", "The following are requirements of the company on commencement of training, which must be provided to the skills development practitioner    Copy of a valid South African identity document or passport   Non-South African citizens are to provide a copy of an identity document or Passport from their respective countries   All identity document copies must be signed by the learner   A black pen is required for filling in enrolment documentation and assessment material    The following are requirements of the learner on commencement of training, which must be handed to the skills development practitioner   A boardroom/dedicated classroom or office for theory training   Overhead projector   Dedicated machine/equipment for practical training and assessment   Dedicated training area for practical training and assessment   Any material/equipment required for practical training such as lifting tackle, a test load or pallets for building a chicane    For additional information regarding course-specific requirements, refer to the respective training categories offered on the website   Requirements for recertification  refresher  training  Providing the training is of an accredited nature where the learner must obtain recertification in order to continue operating,    The National Code of Practice requires the learner to produce proof of previous full training received, in way of a copy of a valid expired training/competency certificate, or copies of expired carry cards   Expiry time frame should be within three months A valid qualification entitles the operator to receive recertification training in one day If a valid competency certificate cannot be produced, i.e., the certificate is expired, full  initial  training must be scheduled over five days   If you have any queries regarding the requirements and conditions of training, feel free to contact our skills development advisor for more information                                                                           Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "Tim SHERQ Consultancy  We provide a wide range of OHSE courses.  ");
   this[database_length++] = new SearchPage("Construction-Site-Safety-Training.html", "Construction Site Safety Training: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "Construction Site Safety Training   Supervisor, Flagman,");
   this[database_length++] = new SearchPage("Construction-Regulations-2014-.html", "Construction Regulations 2014: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Construction Regulations 2014 Training");
   this[database_length++] = new SearchPage("Construction-Site-Flagman.html", "Construction site Flagman: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Construction site Flagman Training");
   this[database_length++] = new SearchPage("Construction-Supervisor.html", "Supervise Safety on a Construction Site: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Supervise Safety on a Construction Site Training");
   this[database_length++] = new SearchPage("Excavation-inspection.html", "Excavation safety inspection: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Excavation safety inspection,Training");
   this[database_length++] = new SearchPage("Crane-Operations-Training.html", "Crane Operations Training: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Crane Operations Training - Mobile crane , overhead crane, truck mountained crane");
   this[database_length++] = new SearchPage("Mobile-Crane.html", "Mobile Crane: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Mobile Crane Training");
   this[database_length++] = new SearchPage("Mountained-Crane.html", "Truck Mounted Crane: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Truck Mounted Crane Training");
   this[database_length++] = new SearchPage("Overhead-Crane.html", "Overhead Crane: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Overhead Crane Training");
   this[database_length++] = new SearchPage("Health-&-Safety-Training.html", "Health & Safety Training: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Health & Safety Training - First Aid, Fire Fighting, SHE REP, HIRA , confined space HAZMAT,Legal liability");
   this[database_length++] = new SearchPage("Basic-Fire-Fighting.html", "Perform Basic Fire Fighting: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Perform Basic Fire FightingTraining");
   this[database_length++] = new SearchPage("incident-investigations.html", "Accident/incident investigation: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Accident/incident investigation Training");
   this[database_length++] = new SearchPage("First-aid-level-1.html", "First Aid Level 1: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY First Aid Level 1 Training");
   this[database_length++] = new SearchPage("HAZMAT-Handling.html", "Handling hazardous chemical substances (HAZMAT): Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Handling hazardous chemical substances  HAZMAT  Training");
   this[database_length++] = new SearchPage("First-aid-level-2.html", "FIRST AID LEVEL 2: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  FIRST AID LEVEL 2 TRAINING");
   this[database_length++] = new SearchPage("SHE-REP.html", "Health and Safety Representative: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Health and Safety Representative Training");
   this[database_length++] = new SearchPage("OHSA.html", "Occupational Health and Safety (OHS) Act: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Occupational Health and Safety  OHS  Act Training");
   this[database_length++] = new SearchPage("HAZMAT-Storage.html", "Stacking and storage of hazardous chemical substances ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Stacking and storage of hazardous chemical substances Training");
   this[database_length++] = new SearchPage("HIRA.html", "Hazard Identification & Risk Assessment (HIRA)", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Hazard Identification & Risk Assessment  HIRA  Training");
   this[database_length++] = new SearchPage("Confined-Space.html", "Confined space entry: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY Confined space entry Training");
   this[database_length++] = new SearchPage("Legal-Liability.html", "LEGAL LIABILITY (OHSA): Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  LEGAL LIABILITY  OHSA  Training");
   this[database_length++] = new SearchPage("Landscape-Tools-Training.html", "Landscape Tools Training: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Landscape Tools Training, lawnmower training, brush cutter training, saw cutter training");
   this[database_length++] = new SearchPage("lawnmowers.html", "Ride-on lawnmower: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Ride-on lawnmower Training");
   this[database_length++] = new SearchPage("brush-cutters.html", "Brush Cutter", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Brush Cutter Training");
   this[database_length++] = new SearchPage("chainsaws.html", "Chainsaw: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Chainsaw Training");
   this[database_length++] = new SearchPage("Lift-Truck-Operations-Training.html", "Lift Truck Operations Training: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Lift Truck Operations Training");
   this[database_length++] = new SearchPage("reachtruck.html", "Advanced Defined Purpose Lift Trucks", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Advanced Defined Purpose Lift Trucks Training, Fork lift training reach truck training ");
   this[database_length++] = new SearchPage("Fork-Lift.html", "Counterbalanced Lift Trucks : Training", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Counterbalanced Lift Trucks,   Fork Lift Training, Reach Truck Training");
   this[database_length++] = new SearchPage("ScaffoldingTrainings.html", " Scaffolding Trainings: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY   Scaffolding Trainings");
   this[database_length++] = new SearchPage("Scaffold-Inspection-&-Safety.html", "Scaffold Inspection and Safety; Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Scaffold Inspection and Safety Training");
   this[database_length++] = new SearchPage("Scaffold-Erecting.html", "Scaffold Erecting", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Scaffold Erecting Training");
   this[database_length++] = new SearchPage("Ladder-inspection.html", "Ladder Inspection and Safety; Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Ladder Inspection and Safety Training");
   this[database_length++] = new SearchPage("Working-at-Heights.html", "Working at heights ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Working at heights Training");
   this[database_length++] = new SearchPage("Scaffold-Team-Leadership.html", "Scaffold Team Leadership Training: Tim SHERQ", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Scaffold Team Leadership Training");
   this[database_length++] = new SearchPage("auditing.php", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Environmental-Audit.html", "Untitled Page", " Water Supply Management,   Waste Water Disposal,   Safe Storage,   Use and Disposal of Hazardous Chemicals,   Air Quality Management,   Energy Management,   Emergency Response Systems,   Fire Prevention and Control Systems,   Noise Management, and so on    Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Construction-Safety-Audit-.html", "Untitled Page", "General Inspection  Site Security  Orderliness and Material Storage  Fire Protection / Prevention  Personal Protective Equipment  Confined Space Procedure  Health Hazard Control  Hazard Communications  Hoists, Cranes, Derricks and Rigging  Heavy Equipment  Motor Vehicles  Electrical Safety  Lockout Tagout  Welding and Cutting  Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Legal-Compliance-Audits’.html", "Untitled Page", "National Environmental Management Act  Environment Conservation Act  Hazardous Substance Act  National Buildings Regulations Act  Compensation For Occupational Injuries And Disease Act   Occupational Health And Safety Act  National Water Act  National Air Quality Act  Road Transportation Act  Transport Appeal Tribunal Act  Noise Control Regulations  Water Service Act  Health Act  Tobacco Controls Act  Green Management Audit  Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("SHERQ-Management-Systems-Audits.html", "Untitled Page", "  ISO 45001 2018  Safety   ISO 14001 2004  Environment   ISO 9001 2008  Quality    Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Gap-Analysis-Audit.html", "Untitled Page", " Checking that all documentation required under the OHSA are in place, such as   A written occupational health and safety policy, A workplace violence and harassment policy   All required postings are displayed in the workplace  Written safe work procedures,  Hazard analysis,  Training records   Checking that all documentation are reviewed   To determine if workers have been provided information and instruction   A physical audit of the workplace to look at  The various hazards in the workplace   The findings will be documented on a formal audit report,  Complete with recommendations for corrective action   Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Social-Audit.html", "Untitled Page", " Upholding Code of Conduct and adhering to local laws protecting factory workers   After the first audit, corrective action plans are implemented to eliminate deficiencies    Further audits are then undertaken to ensure compliance with the corrective action plans    Brands are increasingly under pressure by customers and regulatory authorities   to adhere to higher standards of sustainability, equitable worker conditions and environmental protection    A slight lapse can result in major consumer backlash    In this scenario conducting strict Social Audits has become imperative    Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("consulting.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Environmental-Consulting.html", "Untitled Page", "Browse our services below by clicking on each of the icons to learn more    Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Environmental-Impact-Assessments.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Public Participation Process  Stakeholder Mapping and Management  Social Impact Assessment  Financial Impact Assessment    ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Waste-Management-.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Development of Waste Management Strategies  Development and implementation of Waste Management Plans  Waste Reduction Interventions  Life Cycle Assessment  Carbon Footprint Management  Waste Licenses  Collection , Inventory and Storage  Transportation and Disposal  Recovery , Recycling and Utilization  Landfill Remediation and Rehabilitation  Long term Solid Waste Management Plans  Industrial Waste Water Treatment    ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Water-Resource-Management-.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Water Quality Management  Ecological Risk Assessment  Water Balance Auditing  Water Use Licenses  Industrial Effluent Management  Effluent Treatment and Discharge Solutions      ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Contamination-Assessments.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Development and Implementation of Remediation Plans Sustainable Remediation  Groundwater Monitoring  Soil Assessment  Effluent Treatment and Discharge Solutions      ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Emergency-Evacuation-Plans.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Fire  Rubbish fire, electrical fire, gas fire   Medical Emergency  Heart attack, burns, cuts/lacerations, asthma, poisons   Internal Emergency  Flood, chemical spill, power failure, structural instability   External Emergency  Gas leak, civil disturbance, vehicle accident, severe storm damage   Bomb or Substance Threat  Chemical, biological or radiological threat, suspicious package   Armed or Aggressive Intruder  Building invasion, armed intrusion, assault, act of terrorism   External hazards for example terrorist attack on a facility close to site   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Workplace-inspections-.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Emergency/security procedures and knowledge   Maintenance workshop /Hot work/Electrical safety   Hazardous chemicals – storage, handling and documentation   Machine guarding and potential risks   Storage & racking systems   PPE / spill kits/ first aid kits   Emergency procedures   Housekeeping   Traffic flow • Review of reports on incidents and injuries, training programs, induction and safety meetings   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Project-Life-Cycle-.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Safety-In- Design  SID  services   Tender Review/ Application       Review of the successful tenderer / Principal Contractor Safety Plan s   Liaise during mobilisation / site set up using a proprietary Site Safety Set Up       Quality Safety & Environmental system development, implementation and audits against   International and Local Standards   Self-Insurance Audit Tools   Gap analyses of management systems, legislation and processes  Workplace inspections and risk assessments  Incident Investigations      Review of Contractors safety performance  Project Safety Review / lessons learnt     ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Traffic-Management-Plans.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Development of Traffic Management Plans TMP    TMP implementation   Training     Pedestrian and traffic routing  Traffic controls for each expected interaction  Layout of barriers, walkways  Signs and general arrangements to warn and guide traffic   Requirements for special vehicles   Requirements for loading from side of road onto the site  Travel paths and issues such as places to turn around, access ramps and side roads  Designated delivery and loading/unloading areas  The expected frequency of interaction of vehicles and pedestrians  Roles and responsibilities of persons in the workplace for traffic management  Instructions associated with the control of traffic, including in an emergency    ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("SHERQ-Management-Systems.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Successful project implementation and achievement of certifications to  ISO 45001 2018  Safety   ISO 14001 2004  Environment   ISO 9001 2008  Quality     ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Construction-Safety.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Development of the Client Health and Safety Specification  Development of the Baseline Risk assessment  Application for the Construction Permit to work  Monthly legal compliance site audits of the Principal contractor  Approval of the Health and Safety Plan  OHS Project close out reports      Vetting of sub-contractors  Site Inspections  Development of the project specific safety file  Conducting accident and incident investigations and reporting  Conducting Legal compliance audits on the Sub contractors  Attending of the SHE Committee meeting  Development, implementation and maintenance of the SHE plans  Monitoring of the Client Health and Safety Specification  Liaising and distribution of audit reports to relevant stakeholders    ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Process-Safety-Management-.html", "Untitled Page", "  Gap analyses on new or existing Process Safety Strategies    Perform audits on safety elements that have been implemented    Provide Process Safety training, coaching and mentoring    Conduct a review of Major hazardous Installation reports and assess for further improvements   Provide an understanding on current HAZOP studies and any PHA  Process Hazard Analysis   Assess Emergency Response plans    Assist with trouble shooting operational plants from a Process Safety perspective   Provide a practical approach to Process Safety Information gathering     Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Loss-Prevention-and-HSE-Design.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Fire & Gas Mapping study  Fire Protection Design & Review   Vent sizing  Flare Radiation and Dispersion study  Hazardous Area Classification  Layout Safety Review   Quantitative Risk Assessment  Fire and Explosion Risk Assessment    ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Wayleave-Application.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za    We take over the administrative burden of critical permit applications and allow you to focus resources and skills on core business operations   Tim SHERQ delivers transparent, reliable wayleave and infrastructure protection services to a wide range of industries, including construction companies, telecommunications providers and corporates alike   We operate as your project partner, employing our expertise to deliver service excellence With a national coverage and years of experience in the field, we have developed techniques to streamline processes and optimise results   Let us help you with your wayleave requirements, while you focus on the important aspects of your business   A Wayleave is a right of way granted by a landowner  generally government property  for the purpose of carrying out work on the land  to lay cables or pipes  dog in the road reserve and more    Essentially granting you the right to use of the land without owning it One of the main functions of having a Wayleave in place is to ensure that no damage is done to existing infrastructure, such as power cables, roads, water pipes and more   What we Do   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Safety-Files.html", "Untitled Page", " A Health and Safety File, otherwise known as a ‘Contractor Safety File’ is a record of information focusing on the management of health and safety on construction sites for contractors and sub-contractors It protects the employer from criminal liability and proves compliance to the Occupational Health and Safety Act and Regulations     What do we include in your Health and Safety File  Every Health and Safety File is ‘site specific’ It will be compiled in accordance with the client’s and the site’s safety specifications The overall information requirements remain the same, and the site specific documents will be added When we setup your Health and Safety File, it will consist of the following Documents   Contractor appointment letter  Construction Regulation 5 3  f  of the OHSA  37 2  Agreement between client and contractor Notification of Construction Work Copy of the OHS Act Company Occupational Health and Safety Management Plan Company Occupational Health and Safety Policy Letter of Good Standing  Material Safety Data Sheets for hazardous materials used  if required  Tax clearance certificate  Risk Assessments Safe work procedures  Site Specific  Fall Protection plan  if required  Legal appointment with proof of training  Ex Chief Executive Officer, Risk Assessor, First Aider etc  Incident reporting procedures Incident reports  General Administrative Regulation 9  3  – Annexure 1  Incident registers Reports of accidents Emergency preparedness documents First aid documents Induction records Medical surveillance records Safety communication  e.g Toolbox talks  Safety Plan Registers  task and site specific, e.g Confined space, PPE issue, hand tools etc  Minutes of safety meetings Assessment reports Inspection registers   ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Incident-Investigation-.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za    Root Cause Analysis,   Tap Root Analysis,   Fault Tree Analysis,   Failure Mode and Effects Analysis,   Fish Bone Analysis     Suitable Software Tools are also employed for the accident investigation   Additional support will be taken from Experts and Laboratories dealing with   Forensic Science,   Geology,   Metallurgy ,  Special Equipment/ Electrical Devices    The recommendations will be based on the international and national standards and best safety practices followed in the industry   The Incident Reports submitted by our Team have been accepted by Statutory Authorities and Corporate Management    ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("Workplace-Risk-Assessments.html", "Untitled Page", "Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   Identifying the hazards and prioritised the risk from highest to lowest risk   Assessment will clearly state the inherent risk to health and safety of all persons originating from exposure to each hazard, while considering  The severity of harm that could occur The likelihood of that harm occurring   Recommendations made by Tim SHERQ will be based on best practice and applicable standards   The source of each recommendation will be cited and clearly state the residual risk to health and safety of all persons originating from exposure to each hazard once/if each recommendation is implemented    ", "TIM SHERQ CONSULTANCY  Beyond Health and Safety Compliance");
   this[database_length++] = new SearchPage("contact-us.html", "Contact- Us: Tim SHERQ", "  All fields are required   Email  info@timsherq.co.za Phone  +27 81 413 5910 Fax      +27 86 410 7887   WhatsApp  +27 81 413 5910      ADDRESS      Unit  22  Kloofberg Business Park     17 Spruit Street  Germiston  1401       CONTACTS   I am enquiring about   Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za  Share this page with your friends!   ", "TIM SHERQ CONSULTANCY  Contact- Us   ADDRESS  Unit  22  Kloofberg Business Park 17 Spruit Street  Germiston  1401 Email  info@timsherq.co.za  Phone  +27 81 413 5910 Fax   +27 86 410 7887   WhatsApp  +27 81 413 5910");
   this[database_length++] = new SearchPage("blog.html", "Blog: Tim SHERQ", "Sign up for the newsletter Get notified about new content on my website  Copyright © 2016 by \"Tim SHERQ Consultancy\"·  All Rights reserved·  E-Mail  info@timsherq.co.za   ", "TIM SHERQ CONSULTANCY  Blog   We encourage Legal Compliance on all SHERQ laws and International standards for all sectors of the economy ");
   return this;
}
